"use strict";
const CLIENT_ID="169606052820-5ij848mubicfdppo5b2g5qpaub67munt.apps.googleusercontent.com";
const SCOPE="https://www.googleapis.com/auth/drive.readonly https://www.googleapis.com/auth/userinfo.email";
const ALLOWED_EMAIL="lezaikra553@gmail.com";
const FILES={BM:["berkah_mulia_BM_sync_latest.json","berkah_mulia_portal_sync_latest.json"],DM:["dwi_mulia_portal_sync_latest.json","dwi_mulia_DM_sync_latest.json"],AP:["azkia_mulia_AP_sync_latest.json","azkia_mulia_portal_sync_latest.json"]};
const CN={BM:"Berkah Mulia",DM:"Dwi Mulia",AP:"Azkia Mulia Perada"};
const MN=["Januari","Februari","Maret","April","Mei","Juni","Juli","Agustus","September","Oktober","November","Desember"];
let token="", RAW={cash:[],docs:[],employees:[],payroll:[]};
const $=id=>document.getElementById(id), rp=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n)||0), esc=s=>String(s??"").replace(/[&<>\"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
function safeJson(s){try{return JSON.parse(s)}catch{return null}}
function walk(v,fn,seen=new WeakSet){if(!v||typeof v!=="object")return;if(seen.has(v))return;seen.add(v);fn(v);if(Array.isArray(v))v.forEach(x=>walk(x,fn,seen));else Object.values(v).forEach(x=>walk(x,fn,seen))}
function calcItems(a){return (Array.isArray(a)?a:[]).reduce((s,x)=>s+(Number(x.total)||Number(x.amount)||((Number(x.qty)||1)*(Number(x.price)||0))),0)}
function absorb(company,payload){let storage=payload?.storage||payload?.data?.storage||payload?.localStorage||payload; if(!storage||typeof storage!=="object")return; walk(storage,o=>{if(Array.isArray(o.quotes))o.quotes.forEach(q=>RAW.docs.push({company,type:"Penawaran",name:q.customer||q.client||"-",date:q.date||q.tanggal||"",work:q.perihal||q.subject||q.items?.[0]?.item||"-",nominal:calcItems(q.items||q.details)}));if(Array.isArray(o.invoices))o.invoices.forEach(i=>RAW.docs.push({company,type:"Invoice",name:i.customer||i.client||"-",date:i.date||i.tanggal||"",work:i.po||i.perihal||i.items?.[0]?.desc||"-",nominal:calcItems(i.items||i.details)}));if(o.transactions&&typeof o.transactions==="object"&&!Array.isArray(o.transactions))Object.entries(o.transactions).forEach(([month,tr])=>{if(!tr||typeof tr!=="object")return;const add=(arr,inn,out,pre="")=>(Array.isArray(arr)?arr:[]).forEach(x=>RAW.cash.push({company,month,date:x.date||"",desc:pre+(x.description||x.desc||""),in:inn?Number(x.amount)||0:0,out:out?Number(x.amount)||0:0}));add(tr.pemasukan,1,0);add(tr.operasional,0,1);add(tr.indra,0,1,"Borongan Indra - ");add(tr.andre,0,1,"Borongan Andre - ")})})}
async function findFile(name){const q=encodeURIComponent(`name='${name}' and trashed=false`),r=await fetch(`https://www.googleapis.com/drive/v3/files?q=${q}&spaces=drive&fields=files(id,name,modifiedTime)&pageSize=10`,{headers:{Authorization:"Bearer "+token}}),j=await r.json();if(!r.ok)throw Error(j.error?.message||"Gagal mencari file");return (j.files||[]).sort((a,b)=>String(b.modifiedTime).localeCompare(String(a.modifiedTime)))[0]}
async function syncCompany(c){let f=null;for(const n of FILES[c]){f=await findFile(n);if(f)break}if(!f)throw Error("File backup tidak ditemukan");const r=await fetch(`https://www.googleapis.com/drive/v3/files/${f.id}?alt=media`,{headers:{Authorization:"Bearer "+token}});if(!r.ok)throw Error("Gagal membaca backup");const p=await r.json();localStorage.setItem("OWNER_V4_"+c,JSON.stringify(p));return f.name}
function loadLocal(){RAW={cash:[],docs:[],employees:[],payroll:[]};for(const c of ["BM","DM","AP"]){const p=safeJson(localStorage.getItem("OWNER_V4_"+c));if(p)absorb(c,p)}buildFilters();render()}
function period(x){let s=String(x.month||x.date||"");let m=s.match(/(20\d{2})[-\/]?(\d{1,2})/);if(m)return{y:m[1],m:String(m[2]).padStart(2,"0")};m=s.match(/(\d{1,2})[-\/](\d{1,2})[-\/](20\d{2})/);return m?{y:m[3],m:String(m[2]).padStart(2,"0")}:{y:"",m:""}}
function buildFilters(){const ys=new Set();RAW.cash.forEach(x=>{const p=period(x);if(p.y)ys.add(p.y)});$("year").innerHTML='<option value="ALL">Semua Tahun</option>'+[...ys].sort().reverse().map(y=>`<option>${y}</option>`).join("");$("month").innerHTML='<option value="ALL">Semua Bulan</option>'+MN.map((n,i)=>`<option value="${String(i+1).padStart(2,"0")}">${n}</option>`).join("")}
function filtered(){const c=$("company").value,m=$("month").value,y=$("year").value,ok=x=>{const p=period(x);return(c==="ALL"||x.company===c)&&(m==="ALL"||p.m===m)&&(y==="ALL"||p.y===y)};return{cash:RAW.cash.filter(ok),docs:RAW.docs.filter(ok)}}
function render(){const {cash,docs}=filtered(),ins=cash.reduce((s,x)=>s+x.in,0),outs=cash.reduce((s,x)=>s+x.out,0),profit=ins-outs;$("cards").innerHTML=[["Kas Masuk",rp(ins)],["Kas Keluar",rp(outs)],["Profit Bersih",rp(profit)],["Dokumen",docs.length]].map(x=>`<div class="card">${x[0]}<b>${x[1]}</b></div>`).join("");$("cashCount").textContent=cash.length+" transaksi";$("cashBody").innerHTML=cash.map(x=>`<tr><td>${CN[x.company]}</td><td>${esc(x.month)}</td><td>${esc(x.date)}</td><td>${esc(x.desc)}</td><td class="right">${x.in?rp(x.in):"-"}</td><td class="right">${x.out?rp(x.out):"-"}</td></tr>`).join("")||'<tr><td colspan="6">Belum ada data.</td></tr>';$("docCount").textContent=docs.length+" dokumen";$("docBody").innerHTML=docs.map(x=>`<tr><td>${CN[x.company]}</td><td>${x.type}</td><td>${esc(x.name)}</td><td>${esc(x.date)}</td><td>${esc(x.work)}</td><td class="right">${rp(x.nominal)}</td></tr>`).join("")||'<tr><td colspan="6">Belum ada data.</td></tr>';renderInvestor()}
function stakes(c){return safeJson(localStorage.getItem("OWNER_V4_STAKES_"+c))||({BM:[{name:"Abdul Aziz",pct:60,start:"2026-04"},{name:"Sentot",pct:10,start:"2026-04"},{name:"Tabungan Bersama",pct:30,start:"2026-04"}],DM:[{name:"Dwita Hayani",pct:100,start:"2026-02"}],AP:[{name:"Ade Indra",pct:100,start:"2026-02"}]}[c])}
function renderInvestor(){const c=$("investorCompany").value,mm={};RAW.cash.filter(x=>x.company===c).forEach(x=>{const p=period(x),k=p.y&&p.m?p.y+"-"+p.m:"";if(!k)return;mm[k]??={in:0,out:0};mm[k].in+=x.in;mm[k].out+=x.out});const allStakes=stakes(c),months=Object.entries(mm).sort(),activeNames=[];months.forEach(([k])=>allStakes.filter(s=>k>=s.start).forEach(s=>{if(!activeNames.some(a=>a.name===s.name&&a.pct===s.pct))activeNames.push(s)}));$("investorHead").innerHTML='<th>Bulan</th><th class="right">Laba/Rugi</th>'+activeNames.map(s=>`<th class="right">${s.pct}% ${esc(s.name).toUpperCase()}</th>`).join('');let totals={profit:0};activeNames.forEach((_,i)=>totals[i]=0);$("investorBody").innerHTML=months.map(([k,v])=>{const profit=v.in-v.out,active=allStakes.filter(s=>k>=s.start);totals.profit+=profit;let cells=activeNames.map((s,i)=>{const on=active.some(a=>a.name===s.name&&a.pct===s.pct),val=on&&profit>0?profit*s.pct/100:0;totals[i]+=val;return`<td class="right">${on&&profit>0?rp(val):'-'}</td>`}).join('');return`<tr><td><b>${MN[Number(k.slice(5))-1]} ${k.slice(0,4)}</b></td><td class="right ${profit>=0?'pos':'neg'}">${rp(profit)}</td>${cells}</tr>`}).join('')||'<tr><td colspan="8">Belum ada data.</td></tr>';$("investorFoot").innerHTML=months.length?`<tr><th>TOTAL</th><th class="right">${rp(totals.profit)}</th>${activeNames.map((_,i)=>`<th class="right">${rp(totals[i])}</th>`).join('')}</tr>`:''}
function loginGoogle(){return new Promise((resolve,reject)=>{if(!window.google?.accounts?.oauth2){reject(Error("Google belum siap"));return}google.accounts.oauth2.initTokenClient({client_id:CLIENT_ID,scope:SCOPE,callback:async r=>{if(r.error){reject(Error(r.error));return}token=r.access_token;const u=await fetch("https://www.googleapis.com/oauth2/v3/userinfo",{headers:{Authorization:"Bearer "+token}}).then(x=>x.json());if((u.email||"").toLowerCase()!==ALLOWED_EMAIL){token="";reject(Error("Gunakan akun "+ALLOWED_EMAIL));return}$("status").textContent="Google aktif: "+u.email;resolve()}}).requestAccessToken({prompt:"consent"})})}
$("loginBtn").onclick=()=>{if($("user").value==="owner"&&$("pass").value==="123456"){sessionStorage.setItem("OWNER_V4_LOGIN","1");$("login").hidden=true;$("app").hidden=false;loadLocal()}else $("loginMsg").textContent="Username atau password salah"};$("logoutBtn").onclick=()=>{sessionStorage.clear();location.href=location.pathname};$("googleBtn").onclick=()=>loginGoogle().catch(e=>alert(e.message));$("syncBtn").onclick=async()=>{try{if(!token)await loginGoogle();$("status").textContent="Sedang sinkron...";const out=[];for(const c of ["BM","DM","AP"]){try{out.push(c+": "+await syncCompany(c))}catch(e){out.push(c+": GAGAL - "+e.message)}}loadLocal();$("status").textContent="Sinkron selesai "+new Date().toLocaleString("id-ID");alert(out.join("\n"))}catch(e){alert(e.message)}};$("applyBtn").onclick=render;$("resetBtn").onclick=()=>{$("company").value="ALL";$("month").value="ALL";$("year").value="ALL";render()};$("investorCompany").onchange=renderInvestor;$("editInvestorBtn").onclick=()=>{const c=$("investorCompany").value,cur=stakes(c).map(x=>`${x.name}=${x.pct}=${x.start}`).join("\n"),txt=prompt("Format: Nama=Persen=YYYY-MM",cur);if(txt===null)return;const a=txt.split(/\n+/).map(s=>s.trim()).filter(Boolean).map(s=>{const [name,pct,start]=s.split("=");return{name,pct:Number(pct),start}});if(!a.length||a.some(x=>!x.name||!x.start||!Number.isFinite(x.pct))||Math.round(a.reduce((s,x)=>s+x.pct,0)*100)/100!==100){alert("Data tidak valid. Total persen harus 100%.");return}localStorage.setItem("OWNER_V4_STAKES_"+c,JSON.stringify(a));renderInvestor()};
if(sessionStorage.getItem("OWNER_V4_LOGIN")==="1"){$("login").hidden=true;$("app").hidden=false;loadLocal()}
