'use strict';
const APP_KEY='MULIA_OWNER_CENTER_V1';
const SESSION_KEY='MULIA_OWNER_SESSION';
const COMPANY_DEFS={
 BERKAH:{code:'BERKAH',name:'CV Berkah Mulia Adv',color:'#5b3f91',keys:{sales:['BM_V3_FRESH_SALES_DB_V1','BM_SALES_DB_V1'],cash:['BM_V3_FRESH_KAS_ACTIVE_DB','BM_V3_FRESH_KAS_BESAR','BM_KAS_BESAR_ACTIVE_DB'],hr:['BM_V3_FRESH_ABSENSI_GAJI_V1','BM_V3_UNUSED_OLD_ABSENSI','BM_ABSENSI_GAJI_V4'],projects:['BM_ENTERPRISE_V2','BM_ENTERPRISE_V1'],profit:['BM_BAGI_HASIL_SIMPLE_V1','BM_V3_BAGI_HASIL_SIMPLE_APRIL_2026_V1']}},
 DWI:{code:'DWI',name:'PT Dwi Mulia Advertising',color:'#0f7d76',keys:{sales:['DMA_SALES_DB_V1'],cash:['DMA_KAS_BESAR_ACTIVE_DB'],hr:['DMA_ABSENSI_GAJI_V4'],projects:['DMA_ENTERPRISE_V2','DMA_ENTERPRISE_V1'],profit:['DMA_BAGI_HASIL_SIMPLE_V1']}},
 AZKIA:{code:'AZKIA',name:'PT Azkia Mulia Perada',color:'#b36a1e',keys:{sales:['AP_SALES_DB_V1'],cash:['AP_KAS_BESAR_ACTIVE_DB'],hr:['AP_ABSENSI_GAJI_V4'],projects:['AP_ENTERPRISE_V2','AP_ENTERPRISE_V1'],profit:['AP_BAGI_HASIL_SIMPLE_V1']}}
};
const defaultState={version:1,password:'owner123',group:{name:'Mulia Advertising Group',owner:'Abdul Aziz Efendi',address:'Bekasi, Jawa Barat',phone:'',email:''},snapshots:{},history:[]};
let state=loadState();let activePage='dashboard';let filters={company:'ALL',period:new Date().toISOString().slice(0,7)};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function loadState(){try{return Object.assign(structuredClone(defaultState),JSON.parse(localStorage.getItem(APP_KEY)||'{}'))}catch{return structuredClone(defaultState)}}
function saveState(){localStorage.setItem(APP_KEY,JSON.stringify(state));}
function num(v){v=Number(v);return Number.isFinite(v)?v:0}function money(v){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(num(v))}function dateFmt(v){if(!v)return'-';let d=new Date(v);return isNaN(d)?String(v):d.toLocaleDateString('id-ID')}function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}function toast(msg){let t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600)}
function firstObj(src,keys){for(const k of keys){let v=src?.[k];if(typeof v==='string'){try{v=JSON.parse(v)}catch{}}if(v&&typeof v==='object')return v}return null}
function normalizeBackup(raw,code){const def=COMPANY_DEFS[code];let root=raw?.data&&typeof raw.data==='object'?raw.data:raw; if(raw?.storage&&typeof raw.storage==='object')root=raw.storage; const snap={code,name:def.name,importedAt:new Date().toISOString(),sourceFile:raw.__filename||'',sales:firstObj(root,def.keys.sales)||{},cash:firstObj(root,def.keys.cash)||{},hr:firstObj(root,def.keys.hr)||{},projects:firstObj(root,def.keys.projects)||{},profit:firstObj(root,def.keys.profit)||{}}; if(!Object.keys(snap.sales).length&&!Object.keys(snap.cash).length&&!Object.keys(snap.hr).length){const guessed=guessModules(root);snap.sales=guessed.sales||{};snap.cash=guessed.cash||{};snap.hr=guessed.hr||{};snap.projects=guessed.projects||{};snap.profit=guessed.profit||{}}return snap}
function guessModules(root){const out={};for(const v0 of Object.values(root||{})){let v=v0;if(typeof v==='string'){try{v=JSON.parse(v)}catch{continue}}if(!v||typeof v!=='object')continue;if(Array.isArray(v.invoices)||Array.isArray(v.quotes))out.sales=v;else if(v.transactions&&typeof v.transactions==='object')out.cash=v;else if(Array.isArray(v.employees)&&v.attendance)out.hr=v;else if(Array.isArray(v.projects)||Array.isArray(v.jobs))out.projects=v;else if(Array.isArray(v.shares))out.profit=v}return out}
function docCalc(x){const items=Array.isArray(x.items)?x.items:[];let sub=items.reduce((a,i)=>a+num(i.total||i.amount||num(i.qty)*num(i.price)),0);if(!sub)sub=num(x.subtotal||x.total||x.grandTotal||x.value);let disc=num(x.discountAmount||x.discount);if(num(x.discountPercent))disc+=sub*num(x.discountPercent)/100;let tax=num(x.taxAmount||x.ppnAmount);if(!tax&&num(x.ppnPercent))tax=(sub-disc)*num(x.ppnPercent)/100;let grand=num(x.grandTotal||x.totalAfterTax)||(sub-disc+tax);let paid=(Array.isArray(x.payments)?x.payments:[]).reduce((a,p)=>a+num(p.amount||p.value),0)||num(x.paid||x.paymentTotal);return{grand,paid,sisa:Math.max(0,grand-paid)}}
function txRows(snap){const rows=[];for(const [period,m] of Object.entries(snap.cash?.transactions||{})){for(const x of (m?.pemasukan||[]))rows.push({company:snap.code,date:x.date||period+'-01',desc:x.description||x.keterangan||'Pemasukan',category:x.category||x.source||'Pemasukan',in:num(x.amount),out:0});for(const x of (m?.operasional||m?.pengeluaran||[]))rows.push({company:snap.code,date:x.date||period+'-01',desc:x.description||x.keterangan||'Pengeluaran',category:x.category||x.source||'Operasional',in:0,out:num(x.amount)})}return rows}
function invoiceRows(snap){return (snap.sales?.invoices||[]).map(x=>{const c=docCalc(x),due=x.dueDate||x.jatuhTempo||'',status=c.sisa<=0?'LUNAS':(due&&new Date(due)<new Date()?'TERLAMBAT':'PIUTANG');return{company:snap.code,no:x.number||x.no||x.invoiceNo||x.id||'-',customer:x.customer||x.customerName||x.client||'-',date:x.date||x.invoiceDate||'',due,grand:c.grand,paid:c.paid,sisa:c.sisa,status}})}
function employeeRows(snap){return (snap.hr?.employees||[]).map(e=>({company:snap.code,id:e.id||'',name:e.name||e.nama||'-',position:e.position||e.jabatan||'-',salary:num(e.salary||e.gajiPokok||e.basicSalary)}))}
function projectRows(snap){const arr=snap.projects?.projects||snap.projects?.jobs||[];return arr.map(p=>({company:snap.code,name:p.name||p.projectName||p.title||'-',customer:p.customer||p.client||'-',value:num(p.value||p.contractValue||p.total),hpp:num(p.hpp||p.cost||p.actualCost),progress:num(p.progress||p.percent),status:p.status||'Aktif',start:p.startDate||'',end:p.endDate||''}))}
function profitData(snap){let shares=snap.profit?.shares||[];return{shares,period:snap.profit?.period||'',total:num(snap.profit?.profit||snap.profit?.totalProfit||snap.profit?.distributableProfit)}}
function selectedSnapshots(){return Object.values(state.snapshots).filter(s=>filters.company==='ALL'||s.code===filters.company)}
function allData(){const snaps=selectedSnapshots();return{snaps,tx:snaps.flatMap(txRows),inv:snaps.flatMap(invoiceRows),emp:snaps.flatMap(employeeRows),projects:snaps.flatMap(projectRows),profit:snaps.map(s=>({company:s.code,...profitData(s)}))}}
function periodMatch(date){return !filters.period||String(date||'').slice(0,7)===filters.period}
function render(){populateCompanyFilter();let d=allData();renderDashboard(d);renderCompanies(d);renderCash(d);renderInvoices(d);renderProjects(d);renderPayroll(d);renderProfit(d);renderImports();renderReports();updateLastSync()}
function kpi(label,value,small=''){return `<div class="kpi"><span>${esc(label)}</span><strong>${value}</strong>${small?`<small>${esc(small)}</small>`:''}</div>`}
function renderDashboard(d){let tx=d.tx.filter(x=>periodMatch(x.date)),inv=d.inv, income=tx.reduce((a,x)=>a+x.in,0),expense=tx.reduce((a,x)=>a+x.out,0),receivable=inv.reduce((a,x)=>a+x.sisa,0),payroll=d.emp.reduce((a,x)=>a+x.salary,0);$('#kpiGrid').innerHTML=kpi('Pemasukan Bulan Ini',money(income))+kpi('Pengeluaran Bulan Ini',money(expense))+kpi('Saldo Arus Kas',money(income-expense))+kpi('Total Piutang',money(receivable))+kpi('Estimasi Payroll',money(payroll));$('#healthBanner').className='banner '+(d.snaps.length?'success':'warning');$('#healthBanner').textContent=d.snaps.length?`${d.snaps.length} perusahaan tersinkron. Data ditampilkan dari snapshot terakhir.`:'Belum ada data. Impor backup JSON pada menu Sinkronisasi Data.';
 let max=1, metrics=d.snaps.map(s=>{let t=txRows(s).filter(x=>periodMatch(x.date)),i=t.reduce((a,x)=>a+x.in,0),o=t.reduce((a,x)=>a+x.out,0);max=Math.max(max,i);return{code:s.code,name:s.name,income:i,expense:o}});$('#companyComparison').innerHTML=metrics.length?metrics.map(m=>`<div class="bar-row"><span>${esc(m.name)}</span><div class="bar-track"><div class="bar-fill" style="width:${m.income/max*100}%"></div></div><b class="num">${money(m.income)}</b></div>`).join(''):'<div class="empty">Belum ada data</div>';
 renderCashChart(d.tx);let tops=[...inv].sort((a,b)=>b.sisa-a.sisa).slice(0,6);$('#topReceivables').innerHTML=tops.length?tops.map(x=>`<div class="metric-row"><span>${esc(x.customer)}<small> · ${esc(x.company)}</small></span><b>${money(x.sisa)}</b></div>`).join(''):'<div class="empty">Tidak ada piutang</div>';let recent=[...d.tx].sort((a,b)=>String(b.date).localeCompare(String(a.date))).slice(0,8);$('#recentActivity').innerHTML=recent.length?recent.map(x=>`<div class="metric-row"><span>${dateFmt(x.date)} · ${esc(x.desc)}</span><b class="${x.in?'':'red'}">${money(x.in||-x.out)}</b></div>`).join(''):'<div class="empty">Belum ada transaksi</div>'}
function renderCashChart(rows){let map={};rows.forEach(x=>{let p=String(x.date).slice(0,7);if(!p)return;(map[p]??={in:0,out:0});map[p].in+=x.in;map[p].out+=x.out});let arr=Object.entries(map).sort().slice(-8),max=Math.max(1,...arr.flatMap(([,v])=>[v.in,v.out]));$('#cashChart').innerHTML=arr.length?arr.map(([p,v])=>`<div class="chart-col"><div class="chart-bars"><div class="chart-bar in" title="${money(v.in)}" style="height:${v.in/max*170}px"></div><div class="chart-bar out" title="${money(v.out)}" style="height:${v.out/max*170}px"></div></div><div class="chart-label">${p.slice(5)}/${p.slice(2,4)}</div></div>`).join(''):'<div class="empty">Belum ada data arus kas</div>'}
function renderCompanies(d){$('#companyCards').innerHTML=Object.values(COMPANY_DEFS).map(def=>{let s=state.snapshots[def.code];if(!s)return`<div class="company-card"><h3>${def.name}</h3><span class="pill gray">Belum tersinkron</span><p>Impor backup JSON perusahaan ini melalui menu Sinkronisasi Data.</p></div>`;let tx=txRows(s),inv=invoiceRows(s),emp=employeeRows(s),proj=projectRows(s);return`<div class="company-card"><h3>${def.name}</h3><span class="pill green">Tersinkron</span><div class="metric-row"><span>Pemasukan</span><b>${money(tx.reduce((a,x)=>a+x.in,0))}</b></div><div class="metric-row"><span>Pengeluaran</span><b>${money(tx.reduce((a,x)=>a+x.out,0))}</b></div><div class="metric-row"><span>Piutang</span><b>${money(inv.reduce((a,x)=>a+x.sisa,0))}</b></div><div class="metric-row"><span>Karyawan</span><b>${emp.length}</b></div><div class="metric-row"><span>Proyek</span><b>${proj.length}</b></div><small>Update ${new Date(s.importedAt).toLocaleString('id-ID')}</small></div>`}).join('')}
function renderCash(d){let type=$('#cashType')?.value||'ALL',q=($('#cashSearch')?.value||'').toLowerCase(),rows=d.tx.filter(x=>periodMatch(x.date)&&(type==='ALL'||(type==='IN'&&x.in)||(type==='OUT'&&x.out))&&(!q||(x.desc+x.company+x.category).toLowerCase().includes(q))).sort((a,b)=>String(b.date).localeCompare(String(a.date)));let i=rows.reduce((a,x)=>a+x.in,0),o=rows.reduce((a,x)=>a+x.out,0);$('#cashKpis').innerHTML=kpi('Pemasukan',money(i))+kpi('Pengeluaran',money(o))+kpi('Saldo',money(i-o))+kpi('Jumlah Transaksi',rows.length);$('#cashTable').innerHTML=rows.length?rows.map(x=>`<tr><td>${dateFmt(x.date)}</td><td>${esc(x.company)}</td><td>${esc(x.desc)}</td><td>${esc(x.category)}</td><td class="num">${x.in?money(x.in):'-'}</td><td class="num">${x.out?money(x.out):'-'}</td></tr>`).join(''):'<tr><td colspan="6" class="empty">Tidak ada transaksi</td></tr>'}
function renderInvoices(d){let st=$('#invoiceStatus')?.value||'ALL',q=($('#invoiceSearch')?.value||'').toLowerCase(),rows=d.inv.filter(x=>(st==='ALL'||x.status===st)&&(!q||(x.no+x.customer+x.company).toLowerCase().includes(q))).sort((a,b)=>b.sisa-a.sisa);$('#invoiceKpis').innerHTML=kpi('Nilai Invoice',money(rows.reduce((a,x)=>a+x.grand,0)))+kpi('Terbayar',money(rows.reduce((a,x)=>a+x.paid,0)))+kpi('Sisa Piutang',money(rows.reduce((a,x)=>a+x.sisa,0)))+kpi('Jumlah Invoice',rows.length);$('#invoiceTable').innerHTML=rows.length?rows.map(x=>`<tr><td>${esc(x.no)}</td><td>${esc(x.company)}</td><td>${esc(x.customer)}</td><td>${dateFmt(x.date)}</td><td>${dateFmt(x.due)}</td><td class="num">${money(x.grand)}</td><td class="num">${money(x.paid)}</td><td class="num">${money(x.sisa)}</td><td><span class="pill ${x.status==='LUNAS'?'green':x.status==='TERLAMBAT'?'red':'amber'}">${x.status}</span></td></tr>`).join(''):'<tr><td colspan="9" class="empty">Tidak ada invoice</td></tr>'}
function renderProjects(d){let q=($('#projectSearch')?.value||'').toLowerCase(),rows=d.projects.filter(x=>!q||(x.name+x.customer+x.company).toLowerCase().includes(q));$('#projectKpis').innerHTML=kpi('Jumlah Proyek',rows.length)+kpi('Nilai Kontrak',money(rows.reduce((a,x)=>a+x.value,0)))+kpi('Biaya/HPP',money(rows.reduce((a,x)=>a+x.hpp,0)))+kpi('Estimasi Margin',money(rows.reduce((a,x)=>a+x.value-x.hpp,0)));$('#projectList').innerHTML=rows.length?rows.map(x=>`<div class="project-card"><h3>${esc(x.name)}</h3><span class="pill gray">${esc(x.company)}</span><div class="metric-row"><span>Pelanggan</span><b>${esc(x.customer)}</b></div><div class="metric-row"><span>Nilai</span><b>${money(x.value)}</b></div><div class="metric-row"><span>HPP</span><b>${money(x.hpp)}</b></div><div class="metric-row"><span>Margin</span><b>${money(x.value-x.hpp)}</b></div><div class="metric-row"><span>Progress</span><b>${x.progress}%</b></div><div class="bar-track"><div class="bar-fill" style="width:${Math.min(100,x.progress)}%"></div></div></div>`).join(''):'<div class="empty">Belum ada data proyek</div>'}
function renderPayroll(d){let total=d.emp.reduce((a,x)=>a+x.salary,0);$('#payrollKpis').innerHTML=kpi('Total Karyawan',d.emp.length)+kpi('Estimasi Gaji Pokok',money(total))+kpi('Rata-rata Gaji',money(d.emp.length?total/d.emp.length:0))+kpi('Perusahaan Aktif',new Set(d.emp.map(x=>x.company)).size);let by={};d.emp.forEach(x=>{(by[x.company]??={count:0,total:0});by[x.company].count++;by[x.company].total+=x.salary});$('#payrollByCompany').innerHTML=Object.entries(by).length?Object.entries(by).map(([c,v])=>`<div class="metric-row"><span>${esc(c)} · ${v.count} orang</span><b>${money(v.total)}</b></div>`).join(''):'<div class="empty">Belum ada data karyawan</div>';$('#employeeTable').innerHTML=d.emp.length?`<table><thead><tr><th>Perusahaan</th><th>Nama</th><th>Jabatan</th><th class="num">Gaji Pokok</th></tr></thead><tbody>${d.emp.map(x=>`<tr><td>${esc(x.company)}</td><td>${esc(x.name)}</td><td>${esc(x.position)}</td><td class="num">${money(x.salary)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty">Belum ada data karyawan</div>'}
function renderProfit(d){let count=d.profit.reduce((a,x)=>a+x.shares.length,0),total=d.profit.reduce((a,x)=>a+x.total,0);$('#profitKpis').innerHTML=kpi('Perusahaan',d.profit.length)+kpi('Penerima Bagi Hasil',count)+kpi('Profit Tercatat',money(total))+kpi('Periode Aktif',d.profit.map(x=>x.period).filter(Boolean).join(', ')||'-');$('#profitContent').innerHTML=d.profit.map(x=>`<article class="card"><div class="card-head"><h3>${COMPANY_DEFS[x.company]?.name||x.company}</h3><span class="pill gray">${esc(x.period||'Belum diatur')}</span></div><div>${x.shares.length?x.shares.map(s=>`<div class="metric-row"><span>${esc(s.name||s.nama)}</span><b>${num(s.percent||s.persen)}%</b></div>`).join(''):'<div class="empty">Belum ada konfigurasi bagi hasil</div>'}</div></article>`).join('')||'<div class="empty">Belum ada data bagi hasil</div>'}
function renderImports(){let html='';for(const def of Object.values(COMPANY_DEFS)){let s=state.snapshots[def.code];html+=`<article class="card import-card"><div class="company-color" style="background:${def.color}"></div><h3>${def.name}</h3><p>${s?`Snapshot terakhir: ${new Date(s.importedAt).toLocaleString('id-ID')}`:'Belum pernah diimpor'}</p><label class="btn primary file-btn">Pilih Backup JSON<input type="file" accept="application/json,.json" data-import="${def.code}"></label>${s?` <button class="btn" data-delete-snapshot="${def.code}">Hapus Snapshot</button>`:''}</article>`}$('#importCards').innerHTML=html;$('#importHistory').innerHTML=state.history.length?state.history.slice().reverse().map(h=>`<div class="history-item"><span><b>${esc(h.company)}</b> · ${esc(h.file||'backup.json')}</span><span>${new Date(h.at).toLocaleString('id-ID')}</span></div>`).join(''):'<div class="empty">Belum ada riwayat sinkronisasi</div>';$$('[data-import]').forEach(i=>i.onchange=importCompanyFile);$$('[data-delete-snapshot]').forEach(b=>b.onclick=()=>{delete state.snapshots[b.dataset.deleteSnapshot];saveState();render();toast('Snapshot dihapus')})}
function renderReports(){let cards=[['Executive Report','Ringkasan KPI, kas, piutang, payroll dan proyek.','dashboard'],['Konsolidasi Kas','Daftar pemasukan dan pengeluaran seluruh perusahaan.','cash'],['Invoice & Piutang','Daftar invoice, pembayaran, sisa dan status jatuh tempo.','receivables'],['Monitoring Proyek','Nilai kontrak, HPP, margin dan progres pekerjaan.','projects'],['Payroll Grup','Jumlah karyawan dan estimasi payroll per perusahaan.','payroll'],['Bagi Hasil','Komposisi pembagian hasil dan modal.','profit']];$('#reportCards').innerHTML=cards.map(([t,d,p])=>`<div class="report-card"><h3>${t}</h3><p>${d}</p><button class="btn primary" onclick="openAndPrint('${p}')">Buka & Print</button></div>`).join('')}
function populateCompanyFilter(){let sel=$('#globalCompanyFilter'),v=filters.company;sel.innerHTML='<option value="ALL">Semua Perusahaan</option>'+Object.values(COMPANY_DEFS).map(x=>`<option value="${x.code}">${x.name}</option>`).join('');sel.value=v}
function updateLastSync(){let times=Object.values(state.snapshots).map(x=>x.importedAt).sort();$('#lastSync').textContent=times.length?'Sinkron '+new Date(times.at(-1)).toLocaleString('id-ID'):'Belum ada sinkronisasi'}
async function importCompanyFile(e){let file=e.target.files[0];if(!file)return;try{let raw=JSON.parse(await file.text());raw.__filename=file.name;let code=e.target.dataset.import,snap=normalizeBackup(raw,code);if(!Object.keys(snap.sales).length&&!Object.keys(snap.cash).length&&!Object.keys(snap.hr).length)throw Error('Struktur data perusahaan tidak dikenali');state.snapshots[code]=snap;state.history.push({company:COMPANY_DEFS[code].name,file:file.name,at:snap.importedAt});state.history=state.history.slice(-100);saveState();render();toast('Data '+COMPANY_DEFS[code].name+' berhasil disinkronkan')}catch(err){alert('Gagal membaca backup: '+err.message)}finally{e.target.value=''}}
function switchPage(page){activePage=page;$$('.page').forEach(x=>x.classList.toggle('active',x.id==='page-'+page));$$('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===page));let titles={dashboard:['Dashboard Grup','Ringkasan seluruh perusahaan'],companies:['Perusahaan','Kinerja per entitas usaha'],cash:['Konsolidasi Kas','Pemasukan dan pengeluaran grup'],receivables:['Invoice & Piutang','Monitoring pembayaran pelanggan'],projects:['Monitoring Proyek','Nilai, biaya, margin dan progres'],payroll:['Absensi & Payroll','Ringkasan SDM seluruh perusahaan'],profit:['Bagi Hasil & Modal','Distribusi profit dan kepemilikan modal'],imports:['Sinkronisasi Data','Impor backup dari aplikasi perusahaan'],reports:['Pusat Laporan','Cetak dan simpan PDF'],settings:['Pengaturan','Identitas grup dan keamanan']};$('#pageTitle').textContent=titles[page][0];$('#pageSubtitle').textContent=titles[page][1];$('.sidebar').classList.remove('open');render()}
function csvDownload(name,headers,rows){let q=v=>'"'+String(v??'').replace(/"/g,'""')+'"',csv='\ufeff'+headers.map(q).join(',')+'\n'+rows.map(r=>r.map(q).join(',')).join('\n'),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function openAndPrint(page){switchPage(page);setTimeout(()=>window.print(),100)}window.openAndPrint=openAndPrint;
function init(){if(sessionStorage.getItem(SESSION_KEY)==='1')showApp();$('#globalPeriod').value=filters.period;$$('#nav button').forEach(b=>b.onclick=()=>switchPage(b.dataset.page));$('#menuBtn').onclick=()=>$('.sidebar').classList.toggle('open');$('#refreshBtn').onclick=render;$('#printBtn').onclick=()=>window.print();$('#logoutBtn').onclick=()=>{sessionStorage.removeItem(SESSION_KEY);location.reload()};$('#globalCompanyFilter').onchange=e=>{filters.company=e.target.value;render()};$('#globalPeriod').onchange=e=>{filters.period=e.target.value;render()};['cashType','cashSearch','invoiceStatus','invoiceSearch','projectSearch'].forEach(id=>$('#'+id).addEventListener(id.includes('Search')?'input':'change',render));
 $('#loginForm').onsubmit=e=>{e.preventDefault();if($('#loginUser').value.trim().toLowerCase()==='owner'&&$('#loginPass').value===state.password){sessionStorage.setItem(SESSION_KEY,'1');showApp()}else alert('Nama pengguna atau password salah')};
 $('#clearImports').onclick=()=>{if(confirm('Hapus seluruh snapshot perusahaan dari aplikasi owner?')){state.snapshots={};state.history=[];saveState();render()}};
 $('#exportCash').onclick=()=>{let rows=allData().tx;csvDownload('konsolidasi-kas.csv',['Tanggal','Perusahaan','Keterangan','Kategori','Pemasukan','Pengeluaran'],rows.map(x=>[x.date,x.company,x.desc,x.category,x.in,x.out]))};
 $('#exportInvoices').onclick=()=>{let rows=allData().inv;csvDownload('invoice-piutang.csv',['Invoice','Perusahaan','Pelanggan','Tanggal','Jatuh Tempo','Nilai','Terbayar','Sisa','Status'],rows.map(x=>[x.no,x.company,x.customer,x.date,x.due,x.grand,x.paid,x.sisa,x.status]))};
 $('#exportProjects').onclick=()=>{let rows=allData().projects;csvDownload('monitoring-proyek.csv',['Perusahaan','Proyek','Pelanggan','Nilai','HPP','Margin','Progress','Status'],rows.map(x=>[x.company,x.name,x.customer,x.value,x.hpp,x.value-x.hpp,x.progress,x.status]))};
 $('#groupForm').onsubmit=e=>{e.preventDefault();state.group={name:$('#groupName').value,owner:$('#ownerName').value,address:$('#groupAddress').value,phone:$('#groupPhone').value,email:$('#groupEmail').value};saveState();toast('Identitas grup disimpan')};
 $('#passwordForm').onsubmit=e=>{e.preventDefault();if($('#oldPassword').value!==state.password)return alert('Password lama salah');state.password=$('#newPassword').value;saveState();e.target.reset();toast('Password berhasil diganti')};
 $('#exportOwnerBackup').onclick=()=>{let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='mulia-owner-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)};
 $('#restoreOwnerBackup').onchange=async e=>{try{let x=JSON.parse(await e.target.files[0].text());if(!x.group||!x.snapshots)throw Error('Format tidak valid');state=x;saveState();loadSettings();render();toast('Backup owner dipulihkan')}catch(err){alert(err.message)}e.target.value=''};loadSettings();render()}
function loadSettings(){$('#groupName').value=state.group.name||'';$('#ownerName').value=state.group.owner||'';$('#groupAddress').value=state.group.address||'';$('#groupPhone').value=state.group.phone||'';$('#groupEmail').value=state.group.email||''}
function showApp(){$('#loginScreen').classList.add('hidden');$('#app').classList.remove('hidden')}
init();
